nextApp:
  component: ./node_modules/@sls-next/serverless-component
  inputs:
    runtime: ${env.NODE_VERSION}
    bucketRegion: ${env.AWS_REGION}
    bucketName: ${env.S3_BUCKET}
    description: aws:states:opt-out
    build:
      postBuildCommands:
        - node ./deployment_scripts/post-build.js
    publicDirectoryCache:
      value: public, max-age=0, must-revalidate
      test: /\.(gif|jpe?g|png|txt|xml)$/i
    cloudfront:
      defaults:
        forward:
          headers:
            - CloudFront-Is-Desktop-Viewer
            - CloudFront-Is-Mobile-Viewer
            - CloudFront-Is-Tablet-Viewer
            - Host
      origins:
        - url: https://avico-global-domain-images.s3.amazonaws.com
          pathPatterns:
            /images/*:
              minTTL: 10
              maxTTL: 10
              defaultTTL: 10
              allowedHttpMethods:
                - GET
                - HEAD
      restrictions:
        geoRestriction:
          restrictionType: whitelist
          items:
            - US
            - IN
      priceClass: PriceClass_200
      comment: Next Web App Cloudfront Distribution
      paths:
        - /*
    name:
      defaultLambda: ${env.DEFAULT_LAMBDA_NAME}
      apiLambda: ${env.API_LAMBDA_NAME}
      imageLambda: ${env.IMAGE_LAMBDA_NAME}
